# Open Project page -- lists prior projects with search/sort/grid-list view,
# replacing the old inline project list in the File dropdown (base.html).
from plexora import app, get_config, paths
from plexora.server import plugins as plugin_registry
from plexora.server.models import data_model
from plexora.server.models.adapters.inspection import source_layers, source_obsm
from plexora.server.models.project import ROLE_LABELS, ROLE_NAMES, Project
from plexora.server.routes import tool_routes
from plexora.server.routes.page_routes import template_data

from flask import render_template, jsonify, redirect, request, send_file, abort
from pathlib import Path
import datetime
import io
import shutil


def _base_url():
    return app.config.get('PLEXORA_BASE_URL', '')

_THUMBNAIL_CACHE_NAME = '.thumbnail.webp'


@app.route('/open_project')
def open_project_page():
    return render_template('open_project.html', data=template_data())


def _fallback_timestamp(name, home_root=None):
    """Best-effort date for projects saved before createdAt/lastOpenedAt
    existed: macOS reports true creation time via st_birthtime, everything
    else falls back to st_ctime (metadata-change time, the closest
    approximation available)."""
    try:
        stat = paths.project_dir(name, home_root).stat()
    except OSError:
        return None
    seconds = getattr(stat, 'st_birthtime', stat.st_ctime)
    return datetime.datetime.fromtimestamp(seconds).isoformat()


@app.route('/projects')
def list_projects():
    config = get_config()
    # Which root each name came from, read once for the whole listing rather
    # than per project -- `shared` decides whether the card offers rename and
    # delete, so it cannot be left for the client to guess.
    homes = Project.load_roots()
    own = paths.data_root()
    projects = []
    for name, entry in config.items():
        entry = entry or {}
        home_root = homes.get(name)
        created_at = entry.get('createdAt') or _fallback_timestamp(name, home_root)
        last_opened_at = entry.get('lastOpenedAt') or created_at
        projects.append({
            'name': name,
            'createdAt': created_at,
            'lastOpenedAt': last_opened_at,
            'thumbnailUrl': f'/project_thumbnail/{name}',
            'shared': home_root is not None and home_root != own,
        })
    return jsonify(projects)


@app.route('/project_thumbnail/<string:name>')
def project_thumbnail(name):
    config = get_config()
    if name not in config:
        abort(404)

    # A derived image, so it follows the same rule as every other derived
    # artifact: beside the project when that root takes writes, in this user's
    # own root when it does not.
    cache_path = paths.derived_root(name) / _THUMBNAIL_CACHE_NAME
    if cache_path.exists():
        return send_file(cache_path, mimetype='image/webp')

    result = data_model.generate_thumbnail(name)
    if result is None:
        abort(404)
    encoded, mimetype = result
    try:
        cache_path.write_bytes(encoded)
    except OSError:
        pass  # Cache is best-effort -- still serve the freshly generated bytes.
    return send_file(io.BytesIO(encoded), mimetype=mimetype)


# --------------------------------------------------------------------------
# Editing an existing project
#
# The old edit page read a project as if its source file were a CSV, rendered
# the CSV column-matching screen, and posted to a handler that rebuilt the
# config entry from `{}` -- which discarded the data type and the AnnData read
# spec, repointed the source at a CSV that did not exist, and reported the
# whole thing as HTTP 200. Editing an AnnData project destroyed it, silently.
#
# What replaces it is generated from the project record, so it shows only the
# fields that project actually has, and saves through Project.patch(), which
# merges. There is no code path here that can drop a key it did not name.
# --------------------------------------------------------------------------

@app.route('/edit_config/<string:name>')
@app.route('/edit_config', methods=['GET'])
def edit_project_page(name=None):
    name = name or request.args.get('config')
    project = Project.find(name) if name else None
    if project is None:
        return redirect(f"{_base_url()}/open_project")

    return render_template('project_edit.html', data=template_data(
        datasetName=name,
        project=_describe(project),
        needs=_needs_for_tool(project, request.args.get('needs')),
    ))


def known_layers(project):
    """The project with `dataset.layers` filled in, reading the file when they
    were never recorded.

    In memory only -- nothing is written back, so this is safe on the GET paths
    that render a picker. Shared with tool_routes, which needs the same list to
    put the matrix question in the requirements modal: without the backfill, a
    project imported before layers were recorded would be offered a choice of
    one, which is exactly the project that most needs the choice.
    """
    if project.dataset and not project.dataset.layers:
        return project.with_layers(source_layers(project.dataset))
    return project


def known_obsm(project):
    """The project with `dataset.obsm` filled in, reading the file when it was
    never recorded.

    Exactly `known_layers`' job for the coordinate question, and needed more
    urgently: a project imported before obsm was recorded had its coordinate
    source chosen by a name heuristic and offers no way to see, let alone
    correct, what was chosen.
    """
    if project.dataset and not project.dataset.obsm:
        return project.with_obsm(source_obsm(project.dataset))
    return project


def _describe(project):
    """The project as the edit page and the requirements modal consume it.

    Deliberately not the raw entry: the page renders sections from `has`, so
    what it asks about is decided here, once, from the record -- rather than by
    a template guessing which fields might apply to which kind of project.
    """
    project = known_obsm(known_layers(project))
    spec = project.dataset
    layers = list(spec.layers) if spec else []
    return {
        "name": project.name,
        "image": {
            "src": project.image.src,
            "kind": project.image.kind,
            "channelCount": project.image.num_channels,
            "size": [project.image.width, project.image.height],
        },
        "segmentation": {
            "src": project.segmentation.source,
            "available": project.segmentation.available,
            "pending": project.segmentation.pending,
            "mode": project.segmentation.mode,
        },
        "data": None if spec is None else {
            "type": spec.type,
            "src": spec.src,
            "table": spec.table,
            "coordinates": dict(spec.coordinates),
            "features": dict(spec.features),
            "subset": dict(spec.subset),
            "isTransformed": spec.is_transformed,
            "layers": layers,
        },
        # Which matrix the intensities are read from, in the same "X" /
        # "layer:<name>" vocabulary the import form's picker uses, plus whether
        # they are log1p'd on the way in. Two halves of one question -- what
        # numbers is this project actually showing.
        "featureSource": project.feature_source,
        "featureOptions": project.feature_options,
        "featureLog": project.log_transformed,
        # Both, because they are different facts. `cellLayer` is what the
        # project resolves to and is what the select shows; `cellLayerChoice`
        # is whether that was a decision or a default, which is the difference
        # between a form the user can leave alone and one that records an
        # override every time it is saved.
        "cellLayer": project.cell_layer,
        "cellLayerChoice": project.cell_layer_choice,
        "cellLayerOptions": project.cell_layer_options,
        "roles": project.roles.to_dict(),
        "roleLabels": dict(ROLE_LABELS),
        # The role selects, in the vocabulary the question is asked in -- obs
        # columns for AnnData and SpatialData, table columns for a CSV. See
        # Project.role_columns; this page and the requirements modal render
        # from the same three keys so they cannot drift.
        "roleColumns": project.role_columns,
        "roleAnswers": project.role_answers,
        "roleDefaults": project.role_defaults,
        # The coordinate question's own material: every obsm array with its
        # shape, every obs column, and the source recorded now. Separate from
        # the role keys because its answer is a read spec rather than a column
        # name -- an obsm array supplies both axes at once.
        "coordinateOptions": project.coordinate_options,
        "singleImage": bool(spec and spec.single_image),
        "rowNumberIds": bool(spec and spec.row_number_ids),
        "editableRoles": _editable_roles(project),
        "columns": {
            "markers": list(project.columns.markers),
            "metadata": list(project.columns.metadata),
        },
        # Which sections the page renders. A project with only an image has no
        # roles to assign and no columns to classify, so it is not shown empty
        # controls for them.
        # Where each of the three scientific resources is served from. Present
        # for every project, and all-local for almost all of them -- the page
        # renders the section either way, because "this is on this machine" is
        # a fact worth stating once somewhere else is possible at all.
        "resources": _resource_view(project),
        "has": {
            "data": project.has_table,
            "columns": project.has_table and spec.type == "csv",
            "readSpec": project.has_table and spec.type in ("anndata", "spatialdata"),
            "segmentation": project.segmentation.requested,
            # Any project with a table. The matrix select needs more than one
            # matrix to be worth showing -- the template guards it on
            # `data.layers`, so a CSV gets the log switch alone -- but that
            # switch is a real question for every format: whether the numbers
            # are raw counts is not something the file says, and a CSV of raw
            # counts is the commonest case of all. This used to be restricted
            # to the formats that state their own marker split, which left CSV
            # projects with no way to reach the transform at all.
            "features": project.has_table,
            # Offered only once there is something to choose between: a project
            # with neither a mask nor coordinates cannot draw cells at all.
            "cellLayer": bool(project.cell_layer_options),
        },
    }


#: What each resource is called on the edit page, and the local path to show
#: when it is here. One table rather than three branches, so the section cannot
#: come to describe one resource in different words from another.
_RESOURCE_LABELS = {
    "image": "Image",
    "segmentation": "Segmentation mask",
    "table": "Cell table",
}


def _resource_view(project):
    """Where this project's image, mask and table are served from.

    Reads the project record only -- no node is contacted. Whether a node is
    ANSWERING is a different question with a different lifetime, and it is
    asked by the Settings page and by the controls that need it; putting it
    here would make opening an edit page wait on a sleeping laptop.
    """
    from plexora.server.models.project import RESOURCE_KINDS

    paths = {
        "image": project.image.src,
        "segmentation": project.segmentation.derived or project.segmentation.source,
        "table": project.dataset.src if project.dataset else None,
    }
    present = {
        "image": bool(project.image.src) or "image" in project.resources,
        "segmentation": project.segmentation.requested or "segmentation" in project.resources,
        "table": project.has_table,
    }
    view = []
    for kind in RESOURCE_KINDS:
        binding = project.resources.get(kind)
        view.append({
            "kind": kind,
            "label": _RESOURCE_LABELS[kind],
            "present": present[kind],
            "provider": "node" if binding is not None else "local",
            "node": binding.node if binding is not None else None,
            "resourceId": binding.resource_id if binding is not None else None,
            "path": None if binding is not None else paths[kind],
        })
    return view


@app.route('/project/<string:name>/resources')
def project_resources(name):
    """This project's resource bindings, and what the registered nodes offer.

    One request because it is one question -- "where could this come from" --
    and the controls need both halves at once. Nodes are probed in parallel
    with each other only in the sense that one failing does not stop the rest:
    a node that is asleep is listed as unreachable rather than omitted, since
    a project may well be pointing at it and the page has to be able to say so.
    """
    from plexora.server.models import nodes as node_registry
    from plexora.server.providers import http as node_http

    project = Project.find(name)
    if project is None:
        return jsonify(error="Unknown project"), 404

    offered = []
    for node in node_registry.load_all().values():
        try:
            hello = node_http.hello(node, timeout=2.5)
            offered.append({
                "name": node.name, "reachable": True,
                "resources": hello.get("resources") or [],
                "capabilities": hello.get("capabilities") or [],
            })
        except Exception as exc:
            offered.append({"name": node.name, "reachable": False,
                            "resources": [], "capabilities": [], "error": str(exc)})
    return jsonify(resources=_resource_view(project), nodes=offered)


@app.route('/project/<string:name>/resources/<string:kind>', methods=['POST'])
def project_attach_resource(name, kind):
    """Point one resource at a node, or bring it back to this machine.

    `node` absent means detach, and then `path` says where the file is on THIS
    machine -- required, because a resource that was on a node has no local
    copy by construction. Detaching leaves every answer the project has
    recorded about the resource -- roles, marker split, coordinate source --
    exactly as they were, because a table that comes home is not a table that
    has to be re-imported.
    """
    from plexora import nodes as node_api

    payload = request.get_json(silent=True) or {}
    node = (payload.get("node") or "").strip()
    resource_id = (payload.get("resource_id") or "").strip()

    if Project.find(name) is None:
        return jsonify(error="Unknown project"), 404
    try:
        if not node:
            node_api.detach(name, kind, path=payload.get("path"))
        elif kind == "table":
            node_api.attach_table(name, node=node, resource_id=resource_id)
        elif kind == "image":
            node_api.attach_image(name, node=node, resource_id=resource_id)
        elif kind == "segmentation":
            node_api.attach_segmentation(name, node=node, resource_id=resource_id)
        else:
            return jsonify(error=f"Unknown resource kind: {kind}"), 400
    except KeyError as exc:
        return jsonify(error=str(exc).strip("'\"")), 400
    except ValueError as exc:
        return jsonify(error=str(exc)), 400
    except Exception as exc:
        return jsonify(error=str(exc)), 502

    return jsonify(ok=True, resources=_resource_view(Project.load(name)))


def _editable_roles(project):
    """Which roles this project's user may reassign.

    All of them, for every format. `cell_id`, `x` and `y` used to be withheld
    from AnnData and SpatialData projects because the adapter synthesizes those
    columns, so repointing the role named a column the loaded table did not
    have. They are answerable now because the answer goes into the read spec
    instead -- which is the only way to say "the mask's label values are in this
    obs column", and without it a segmentation overlay could never line up.
    """
    return list(ROLE_NAMES) if project.has_table else []


def _needs_for_tool(project, tool_name):
    """The requirements a named tool is still missing, so the edit page can
    highlight exactly those fields. This is the no-JavaScript twin of the
    requirements modal -- same question, same answer, different surface."""
    if not tool_name:
        return None
    plugin = plugin_registry.find(app, tool_name)
    if plugin is None or not plugin.requires.applies_to(project):
        return None
    return {
        "tool": plugin.name,
        "label": plugin.label,
        "missing": [r.describe() for r in plugin.requires.missing_from(project)],
        "confirm": [r.describe() for r in plugin.requires.unconfirmed_from(project)],
        "optional": [r.describe() for r in plugin.requires.optional_missing_from(project)],
    }


@app.route('/project/<string:name>', methods=['POST'])
def save_project(name):
    """Apply an edit. Everything except the image can change.

    Merge semantics throughout: a key the request does not mention is carried
    across untouched. The expensive work -- re-reading a new data file,
    converting a new mask -- runs only when that input actually changed, which
    is what makes saving an unchanged form free.
    """
    payload = request.get_json(silent=True) or {}
    project = Project.find(name)
    if project is None:
        return jsonify(success=False, error="Unknown project"), 404

    try:
        changed = _apply_edit(project, payload)
    except ValueError as exc:
        # A bad path or an unreadable file is the user's to fix, and they need
        # to be told which. The old handler returned success=False with HTTP
        # 200 and no message, and the client navigated away regardless.
        return jsonify(success=False, error=str(exc)), 400

    if changed:
        # An answer is only accepted once the file can be read with it, so a
        # role that rewrites the read spec into something the adapter refuses
        # is put back rather than left stored -- see tool_routes.
        error = tool_routes._reload_or_restore(name, project)
        if error:
            return jsonify(success=False, error=error), 400

    project = Project.find(name)
    return jsonify(success=True, reloaded=changed,
                   segmentation_pending=project.segmentation.pending)


def _apply_edit(project, payload):
    """Returns whether anything changed that needs a datasource reload."""
    from plexora.server.routes import import_routes

    changed = False

    if "segmentation" in payload:
        wanted = (payload.get("segmentation") or "").strip() or None
        current = project.segmentation.source
        if (wanted or None) != (current or None):
            if wanted and not Path(wanted).expanduser().exists():
                raise ValueError(f"No such segmentation mask: {wanted}")
            import_routes.attach_segmentation(project.name, wanted)
            changed = True

    swapped = False
    if "data" in payload:
        wanted = (payload.get("data") or "").strip() or None
        current = project.dataset.src if project.dataset else None
        if (wanted or None) != (current or None):
            import_routes.replace_project_data(project.name, wanted, payload)
            changed = True
            swapped = True

    # Only when the file itself did not change: replace_project_data already
    # reads `features_layer` out of this same payload, and applying it twice
    # would validate the new choice against the old file's layer list.
    if not swapped:
        changed = apply_feature_choice(project, payload) or changed

    roles = payload.get("roles")
    columns = payload.get("columns")
    coordinates = payload.get("coordinates")
    single_image = payload.get("single_image")
    row_number_ids = payload.get("row_number_ids")
    # Presence, not truth: "" is the client saying "no override, draw whatever
    # this project resolves to", which is a change worth applying and would be
    # dropped by a plain truthiness test.
    chose_layer = "cellLayer" in payload
    cell_layer = payload.get("cellLayer")
    confirm = payload.get("confirm")
    if (roles or columns or coordinates or single_image or row_number_ids
            or chose_layer or confirm):
        def _apply(current):
            if columns:
                current = current.with_columns(columns.get("markers") or [],
                                               columns.get("metadata") or [])
            # The same helper the requirements modal applies its answers with,
            # so the two surfaces cannot disagree about what a payload means.
            current = tool_routes.apply_column_answers(current, payload)
            if chose_layer:
                current = current.with_cell_layer(cell_layer)
            # Saving this page is the user looking at these values and
            # accepting them, which is exactly what the requirements modal asks
            # for -- so a tool opened afterwards must not ask again.
            return current.with_confirmed(confirm or ())

        Project.mutate(project.name, _apply)
        # A cell-layer choice on its own changes nothing the datasource holds;
        # it is read from the config by the viewer. Reloading for it would
        # re-open the image to record a preference.
        changed = changed or bool(roles or columns or coordinates
                                  or row_number_ids)

    return changed


def apply_feature_choice(project, payload):
    """Point the reader at a matrix and/or switch the log1p transform.

    Shared with the requirements modal (tool_routes), because both surfaces ask
    the same question and getting the answer to stick means the same two writes.
    Returns whether anything changed -- both halves change what every number in
    the app is, so either one needs the datasource re-read.
    """
    layer = payload.get("features_layer")
    has_log = "features_log" in payload
    log = bool(payload.get("features_log"))
    wants_layer = bool(layer) and layer != project.feature_source
    wants_log = has_log and log != project.log_transformed
    if not wants_layer and not wants_log:
        return False

    # Read outside the write lock: the layer list may come off disk, and holding
    # config.json's lock across a file read serializes every other writer behind
    # it for no reason.
    layers = source_layers(project.dataset) if wants_layer else None

    def _change(current):
        # The available list goes in first, so a project imported before it was
        # recorded validates the choice against the file rather than against an
        # empty tuple that would reject every layer.
        if wants_layer:
            current = current.with_layers(layers).with_feature_source(layer)
        if wants_log:
            current = current.with_log_transform(log)
        return current

    Project.mutate(project.name, _change)
    return True


@app.route('/project/<string:name>/delete', methods=['POST'])
def delete_project(name):
    """Remove a project and everything derived for it.

    POST, not GET: this is an irreversible rmtree, and it used to sit behind a
    link that any crawler, prefetcher or stale bookmark could follow.
    """
    project = Project.find(name)
    if project is None:
        return jsonify(success=False, error="Unknown project"), 404
    if project.is_shared:
        # A shared project belongs to whoever provisioned the root it sits on.
        # Refused here rather than allowed to fail against a read-only
        # filesystem, so the answer is a sentence rather than a traceback --
        # and so a WRITABLE shared root cannot let one user delete a project
        # every other user on the machine is working from.
        return jsonify(
            success=False,
            error="This project is on a shared data directory and cannot be "
                  "deleted from Plexora.",
        ), 403

    project.delete()
    # Only this user's own copy of the project directory. For a project the
    # user owns that is the whole of it; there is nothing else anywhere.
    directory = paths.project_state_dir(name)
    if directory.is_dir():
        shutil.rmtree(directory, ignore_errors=True)
    return jsonify(success=True)
