# Open Project page -- lists prior projects with search/sort/grid-list view,
# replacing the old inline project list in the File dropdown (base.html).
from plexora import app, get_config, paths
from plexora.datasource import reregister_image
from plexora.server import plugins as plugin_registry
from plexora.server.models import data_model, datasets, manifest
from plexora.server.models.adapters import is_flat_table
from plexora.server.models.adapters.inspection import source_layers, source_obsm
from plexora.server.models.project import ROLE_LABELS, ROLE_NAMES, Project
from plexora.server.routes import tool_routes
from plexora.server.routes.page_routes import template_data

from flask import render_template, jsonify, redirect, request, send_file, abort
from dataclasses import replace
from pathlib import Path
import datetime
import io
import shutil


def _base_url():
    return app.config.get('PLEXORA_BASE_URL', '')

_THUMBNAIL_CACHE_NAME = '.thumbnail.webp'


@app.route('/open_project')
def open_project_page():
    return render_template('open_project.html', data=template_data())


def _fallback_timestamp(name, home_root=None):
    """Best-effort date for projects saved before createdAt/lastOpenedAt
    existed: macOS reports true creation time via st_birthtime, everything
    else falls back to st_ctime (metadata-change time, the closest
    approximation available)."""
    try:
        stat = paths.project_dir(name, home_root).stat()
    except OSError:
        return None
    seconds = getattr(stat, 'st_birthtime', stat.st_ctime)
    return datetime.datetime.fromtimestamp(seconds).isoformat()


@app.route('/projects')
def list_projects():
    """Every project the user can see, with enough about each to draw a card.

    The five original keys are unchanged and deliberately so -- Figure
    Builder's library renders from this same list. What is added is what a file
    browser needs and a flat grid did not: which dataset holds this project,
    and a five-fact summary of what it has, so a card can say "Mask", "Data" or
    "Needs setup" without two hundred extra requests.
    """
    config = get_config()
    # Which root each name came from, read once for the whole listing rather
    # than per project -- `shared` decides whether the card offers rename and
    # delete, so it cannot be left for the client to guess.
    homes = Project.load_roots()
    own = paths.data_root()
    # Likewise once: one pass over datasets.json rather than a lookup per
    # project, and pruned to what is actually registered so a name whose shared
    # root is not mounted today does not appear inside a folder it cannot be
    # opened from. Pruned in the VIEW only -- nothing is rewritten here.
    holders = datasets.membership(known=config.keys())
    projects = []
    for name, entry in config.items():
        entry = entry or {}
        home_root = homes.get(name)
        created_at = entry.get('createdAt') or _fallback_timestamp(name, home_root)
        last_opened_at = entry.get('lastOpenedAt') or created_at
        project = Project.from_entry(name, entry, home_root=home_root)
        holder = holders.get(name)
        projects.append({
            'name': name,
            'createdAt': created_at,
            'lastOpenedAt': last_opened_at,
            'thumbnailUrl': f'/project_thumbnail/{name}',
            'shared': home_root is not None and home_root != own,
            # The folder this project is in, or null for one at the top level.
            # Name as well as id, so a card in a flattened search result can say
            # where it lives without a second lookup.
            'dataset': ({'id': holder.id, 'name': holder.name} if holder else None),
            # The badges, from the one manifest reader -- so "has data" means
            # here exactly what it means to a plugin deciding whether to open.
            **manifest.summary(project),
        })
    return jsonify(projects)


@app.route('/project_thumbnail/<string:name>')
def project_thumbnail(name):
    config = get_config()
    if name not in config:
        abort(404)

    # A derived image, so it follows the same rule as every other derived
    # artifact: beside the project when that root takes writes, in this user's
    # own root when it does not.
    cache_path = paths.derived_root(name) / _THUMBNAIL_CACHE_NAME
    if cache_path.exists():
        return send_file(cache_path, mimetype='image/webp')

    result = data_model.generate_thumbnail(name)
    if result is None:
        abort(404)
    encoded, mimetype = result
    try:
        cache_path.write_bytes(encoded)
    except OSError:
        pass  # Cache is best-effort -- still serve the freshly generated bytes.
    return send_file(io.BytesIO(encoded), mimetype=mimetype)


# --------------------------------------------------------------------------
# Editing an existing project
#
# The old edit page read a project as if its source file were a CSV, rendered
# the CSV column-matching screen, and posted to a handler that rebuilt the
# config entry from `{}` -- which discarded the data type and the AnnData read
# spec, repointed the source at a CSV that did not exist, and reported the
# whole thing as HTTP 200. Editing an AnnData project destroyed it, silently.
#
# What replaces it is generated from the project record, so it shows only the
# fields that project actually has, and saves through Project.patch(), which
# merges. There is no code path here that can drop a key it did not name.
# --------------------------------------------------------------------------

@app.route('/edit_config/<string:name>')
@app.route('/edit_config', methods=['GET'])
def edit_project_page(name=None):
    name = name or request.args.get('config')
    project = Project.find(name) if name else None
    if project is None:
        return redirect(f"{_base_url()}/open_project")

    return render_template('project_edit.html', data=template_data(
        datasetName=name,
        project=_describe(project),
        needs=_needs_for_tool(project, request.args.get('needs')),
    ))


def known_layers(project):
    """The project with `dataset.layers` filled in, reading the file when they
    were never recorded.

    In memory only -- nothing is written back, so this is safe on the GET paths
    that render a picker. Shared with tool_routes, which needs the same list to
    put the matrix question in the requirements modal: without the backfill, a
    project imported before layers were recorded would be offered a choice of
    one, which is exactly the project that most needs the choice.
    """
    if project.dataset and not project.dataset.layers:
        return project.with_layers(source_layers(project.dataset))
    return project


def known_obsm(project):
    """The project with `dataset.obsm` filled in, reading the file when it was
    never recorded.

    Exactly `known_layers`' job for the coordinate question, and needed more
    urgently: a project imported before obsm was recorded had its coordinate
    source chosen by a name heuristic and offers no way to see, let alone
    correct, what was chosen.
    """
    if project.dataset and not project.dataset.obsm:
        return project.with_obsm(source_obsm(project.dataset))
    return project


def _describe(project):
    """The project as the edit page and the requirements modal consume it.

    Deliberately not the raw entry: the page renders sections from `has`, so
    what it asks about is decided here, once, from the record -- rather than by
    a template guessing which fields might apply to which kind of project.
    """
    project = known_obsm(known_layers(project))
    spec = project.dataset
    layers = list(spec.layers) if spec else []
    return {
        "name": project.name,
        # Every layer this sample draws, the reference and the mask included.
        # `manifest.layers` rather than a second walk of `all_layers` here, so
        # the edit page and a plugin asking the same question get the same
        # answer.
        "layers": manifest.layers(project),
        "image": {
            "src": project.image.src,
            "kind": project.image.kind,
            "channelCount": project.image.num_channels,
            "size": [project.image.width, project.image.height],
            # True when there is no image file behind this sample at all. The
            # edit page reads it to say so rather than printing an empty path,
            # and to keep the Scale section -- which is the one control on that
            # page a blank frame genuinely has, because its micron-per-pixel is
            # what every layer registered against it was scaled by.
            "blank": project.image.is_blank,
        },
        # The same split the cell layer makes, for the same reason. `imageType`
        # is how the image is actually being read and is what the select shows;
        # `imageTypeChoice` is whether that was a decision or the detector's
        # default. `imageTypeReason` is the detector's own sentence, shown next
        # to the Automatic option so the user can tell whether overriding it is
        # warranted -- absent for a project imported before any of this existed.
        "imageType": project.image_type,
        "imageTypeChoice": project.image.image_type_choice,
        "imageTypeDetected": project.image.image_type_detected,
        "imageTypeReason": project.image.image_type_reason,
        "segmentation": {
            # The node address when the mask is on one, because this is the
            # value the field posts back: showing a blank here would make
            # saving an unrelated setting read as "the user cleared the mask".
            "src": _segmentation_field(project),
            "available": project.segmentation.available,
            "pending": project.segmentation.pending,
            "mode": project.segmentation.mode,
        },
        "data": None if spec is None else {
            "type": spec.type,
            "src": spec.src,
            "table": spec.table,
            "coordinates": dict(spec.coordinates),
            "features": dict(spec.features),
            "subset": dict(spec.subset),
            "isTransformed": spec.is_transformed,
            "layers": layers,
            # What this source still needs before it can be read -- empty for
            # almost every project. The Data field inspects on mount when it is
            # not, so the table select arrives already populated rather than
            # only after the user retypes a path they already gave.
            "unresolved": list(spec.unresolved),
        },
        # Which matrix the intensities are read from, in the same "X" /
        # "layer:<name>" vocabulary the import form's picker uses, plus whether
        # they are log1p'd on the way in. Two halves of one question -- what
        # numbers is this project actually showing.
        "featureSource": project.feature_source,
        "featureOptions": project.feature_options,
        "featureLog": project.log_transformed,
        # Both, because they are different facts. `cellLayer` is what the
        # project resolves to and is what the select shows; `cellLayerChoice`
        # is whether that was a decision or a default, which is the difference
        # between a form the user can leave alone and one that records an
        # override every time it is saved.
        "cellLayer": project.cell_layer,
        "cellLayerChoice": project.cell_layer_choice,
        "cellLayerOptions": project.cell_layer_options,
        "roles": project.roles.to_dict(),
        "roleLabels": dict(ROLE_LABELS),
        # The role selects, in the vocabulary the question is asked in -- obs
        # columns for AnnData and SpatialData, table columns for a CSV. See
        # Project.role_columns; this page and the requirements modal render
        # from the same three keys so they cannot drift.
        "roleColumns": project.role_columns,
        "roleAnswers": project.role_answers,
        "roleDefaults": project.role_defaults,
        # The coordinate question's own material: every obsm array with its
        # shape, every obs column, and the source recorded now. Separate from
        # the role keys because its answer is a read spec rather than a column
        # name -- an obsm array supplies both axes at once.
        "coordinateOptions": project.coordinate_options,
        "singleImage": bool(spec and spec.single_image),
        "rowNumberIds": bool(spec and spec.row_number_ids),
        "editableRoles": _editable_roles(project),
        "columns": {
            "markers": list(project.columns.markers),
            "metadata": list(project.columns.metadata),
        },
        # Which sections the page renders. A project with only an image has no
        # roles to assign and no columns to classify, so it is not shown empty
        # controls for them.
        # Where each of the three scientific resources is served from. Present
        # for every project, and all-local for almost all of them -- the page
        # renders the section either way, because "this is on this machine" is
        # a fact worth stating once somewhere else is possible at all.
        "resources": _resource_view(project),
        # Every question core can record an answer to, with whether it was
        # answered or guessed. The page does not render from this yet; it is
        # here because the edit page, the requirements modal, the project card
        # and the CLI all used to work "does this project have a table?" out
        # separately, and every `has` boolean below is now one read of it.
        "manifest": manifest.manifest(project),
        "summary": manifest.summary(project),
        "has": {
            # A file the user named, readable or not -- the Data SECTION shows
            # for both, since an unresolved source is precisely the project
            # whose path needs to be visible and editable.
            "dataSource": project.has_data_source,
            "data": manifest.answered(project, "table"),
            "columns": project.has_table and is_flat_table(spec.type),
            "readSpec": project.has_table and spec.type in ("anndata", "spatialdata"),
            "segmentation": manifest.answered(project, "segmentation"),
            # Any project with a table. The matrix select needs more than one
            # matrix to be worth showing -- the template guards it on
            # `data.layers`, so a CSV gets the log switch alone -- but that
            # switch is a real question for every format: whether the numbers
            # are raw counts is not something the file says, and a CSV of raw
            # counts is the commonest case of all. This used to be restricted
            # to the formats that state their own marker split, which left CSV
            # projects with no way to reach the transform at all.
            "features": project.has_table,
            # Offered only once there is something to choose between: a project
            # with neither a mask nor coordinates cannot draw cells at all.
            "cellLayer": bool(project.cell_layer_options),
        },
    }


def _segmentation_field(project):
    """What the edit page's Segmentation Mask field shows, and posts back.

    A local mask shows its source path. One on a node shows `node://…`, which
    is the same vocabulary the import form's fields take -- so the field is
    round-trippable for both, and `_apply_edit` can tell "unchanged" from "the
    user cleared it" without consulting the binding a second time.
    """
    from plexora.server.providers.base import node_locator

    binding = project.resource("segmentation")
    if binding is not None:
        return node_locator(binding.node, binding.resource_id)
    return project.segmentation.source


#: What each resource is called on the edit page, and the local path to show
#: when it is here. One table rather than three branches, so the section cannot
#: come to describe one resource in different words from another.
_RESOURCE_LABELS = {
    "image": "Image",
    "segmentation": "Segmentation mask",
    "table": "Cell table",
}


def _resource_view(project):
    """Where this project's image, mask and table are served from.

    Reads the project record only -- no node is contacted. Whether a node is
    ANSWERING is a different question with a different lifetime, and it is
    asked by the Settings page and by the controls that need it; putting it
    here would make opening an edit page wait on a sleeping laptop.
    """
    from plexora.server.models.project import RESOURCE_KINDS

    paths = {
        "image": project.image.src,
        "segmentation": project.segmentation.derived or project.segmentation.source,
        "table": project.dataset.src if project.dataset else None,
    }
    present = {
        # A blank frame has no bytes anywhere, so it is not a resource this
        # section can show a path for or repoint at a node -- and offering a
        # row for it would invite the user to fix something that is not broken.
        "image": ((bool(project.image.src) and not project.image.is_blank)
                  or "image" in project.resources),
        "segmentation": project.segmentation.requested or "segmentation" in project.resources,
        # The FILE, not a readable table: this section is about where bytes
        # come from, and a store whose table is undecided is still a file
        # sitting on this machine or on a node.
        "table": project.has_data_source,
    }
    view = []
    for kind in RESOURCE_KINDS:
        binding = project.resources.get(kind)
        view.append({
            "kind": kind,
            "label": _RESOURCE_LABELS[kind],
            "present": present[kind],
            "provider": "node" if binding is not None else "local",
            "node": binding.node if binding is not None else None,
            "resourceId": binding.resource_id if binding is not None else None,
            "path": None if binding is not None else paths[kind],
        })
    return view


@app.route('/project/<string:name>/manifest')
def project_manifest(name):
    """What this project has, what it was told, and what is still open.

    One read of the same rules every other surface uses -- so a notebook, the
    CLI and a plugin's own server code can ask "is this project set up?"
    without reimplementing the answer or scraping the edit page.
    """
    project = Project.find(name)
    if project is None:
        return jsonify(success=False, error="Unknown project"), 404
    return jsonify(success=True, name=project.name,
                   manifest=manifest.manifest(project),
                   summary=manifest.summary(project))


@app.route('/project/<string:name>/layers/<path:layer_id>', methods=['DELETE'])
def project_remove_layer(name, layer_id):
    """Stop drawing one registered layer.

    The registration only. The file it was read from is the user's and Plexora
    never owned it -- it opened it and remembered where it was -- so removing a
    layer from a sample must not be capable of deleting anybody's data. Derived
    artefacts built FROM it (a transcript tile cache) are Plexora's own and are
    left in place too: re-adding the layer then costs nothing, and a directory
    of caches is cheap next to re-reading a 6 GB parquet.

    The synthesized ids are refused rather than silently ignored: the way to
    remove the mask is to clear the mask field, and an X that quietly did
    nothing would be worse than no X.
    """
    from plexora.server.models.project import RESERVED_LAYER_IDS

    if layer_id in RESERVED_LAYER_IDS:
        return jsonify(error=f"{layer_id} is drawn from the project itself. "
                             "Remove what it is made of instead."), 400
    project = Project.find(name)
    if project is None:
        return jsonify(error=f"Unknown project: {name!r}"), 404
    if project.layer(layer_id) is None:
        return jsonify(error=f"{name} has no layer {layer_id!r}"), 404
    Project.mutate(name, lambda current: current.without_layer(layer_id))
    return jsonify(success=True, layer=layer_id)


@app.route('/project/<string:name>/layers/order', methods=['PUT'])
def project_order_layers(name):
    """Restack this project's registered layers, bottom of the stack first.

    Its own route, and ahead of the PATCH below so a layer that happens to be
    called `order` cannot shadow it: Flask matches in registration order and
    `<path:layer_id>` would otherwise swallow this.

    Order is stored because it is a statement about the sample -- which slide
    is on top of which -- and not about this browser tab. It survives a reload
    for the same reason a registration does.

    The reference image may be named here along with the rest, and it is the
    only synthesized layer that may: which image was imported first should not
    decide which one can be drawn on top. What is kept for it is a depth rather
    than a position -- see `Project.with_layer_order`. The mask and the
    centroids are still placed by `all_layers` every time it is read, because
    where those composite is a fact about the viewer rather than a choice.
    """
    project = Project.find(name)
    if project is None:
        return jsonify(error=f"Unknown project: {name!r}"), 404
    payload = request.get_json(silent=True) or {}
    ids = payload.get('ids')
    if not isinstance(ids, list):
        return jsonify(error="`ids` must be a list of layer ids, bottom first."), 400
    try:
        Project.mutate(name, lambda current: current.with_layer_order(ids))
    except ValueError as error:
        return jsonify(error=str(error)), 400
    saved = Project.find(name)
    return jsonify(success=True,
                   ids=[layer.id for layer in saved.spatial_layers],
                   imageDepth=saved.image_depth)


@app.route('/project/<string:name>/layers/<path:layer_id>', methods=['PATCH'])
def project_update_layer(name, layer_id):
    """How one registered layer is drawn: shown or hidden, and its `render`.

    `render` is the per-kind presentation bag the server never acts on -- the
    opacity, the channel list, the colours and their contrast windows. Merged
    rather than replaced, so a card changing the colour does not silently drop
    the window it was not asked about; `null` for a key removes it, which is
    how "use the file's own" is said.

    Stored because these are statements about the sample rather than about
    this tab. The Layers panel wrote all of them into memory and none of them
    anywhere, so every choice survived exactly until a reload -- a control
    that works and then quietly forgets is worse than one that refuses.

    THE REFERENCE IMAGE accepts a `render` and nothing else. It is synthesized
    from `ImageSpec` rather than stored, so what arrives here is kept beside
    the project as `imageRender` and handed back out by `reference_layer`. Its
    `visible` is not stored: an eye is about this tab, and the image is the one
    layer whose absence leaves the viewer with no world at all.

    The mask and the centroids are still refused, as DELETE refuses them: the
    mask's opacity is the Cells footer's, and storing one here would be a
    second answer that nothing reads.
    """
    from plexora.server.models.project import (REFERENCE_LAYER_ID,
                                               RESERVED_LAYER_IDS)

    if layer_id in RESERVED_LAYER_IDS and layer_id != REFERENCE_LAYER_ID:
        return jsonify(error=f"{layer_id} is drawn from the project itself. "
                             "How it is drawn is not stored with it."), 400
    project = Project.find(name)
    if project is None:
        return jsonify(error=f"Unknown project: {name!r}"), 404
    existing = project.layer(layer_id)
    if existing is None:
        return jsonify(error=f"{name} has no layer {layer_id!r}"), 404

    payload = request.get_json(silent=True) or {}
    changes = {}
    if 'visible' in payload:
        changes['visible'] = payload['visible'] is not False
    if 'render' in payload:
        patch = payload['render']
        if not isinstance(patch, dict):
            return jsonify(error="`render` must be an object."), 400
        merged = dict(existing.render)
        for key, value in patch.items():
            if value is None:
                merged.pop(key, None)
            else:
                merged[key] = value
        changes['render'] = merged
    if not changes:
        return jsonify(error="Nothing to change: send `visible` or `render`."), 400

    if layer_id == REFERENCE_LAYER_ID:
        if 'render' not in changes:
            return jsonify(error="The reference image stores `render` only."), 400
        # Without `imageKind`, which `reference_layer` puts back on every read
        # off the file itself. Storing it would freeze today's answer into the
        # config and outlive a re-import that corrected it.
        merged = {key: value for key, value in changes['render'].items()
                  if key != 'imageKind'}
        Project.mutate(name, lambda current: current.patch(image_render=merged))
    else:
        Project.mutate(name, lambda current: current.with_layer(
            replace(current.layer(layer_id), **changes)))
    return jsonify(success=True, layer=Project.find(name).layer(layer_id).to_entry())


@app.route('/project/<string:name>/resources')
def project_resources(name):
    """This project's resource bindings, and what the registered nodes offer.

    One request because it is one question -- "where could this come from" --
    and the controls need both halves at once. Nodes are probed in parallel
    with each other only in the sense that one failing does not stop the rest:
    a node that is asleep is listed as unreachable rather than omitted, since
    a project may well be pointing at it and the page has to be able to say so.
    """
    from plexora.server.models import nodes as node_registry
    from plexora.server.providers import http as node_http

    project = Project.find(name)
    if project is None:
        return jsonify(error="Unknown project"), 404

    offered = []
    for node in node_registry.load_all().values():
        try:
            hello = node_http.hello(node, timeout=2.5)
            offered.append({
                "name": node.name, "reachable": True,
                "resources": hello.get("resources") or [],
                "capabilities": hello.get("capabilities") or [],
            })
        except Exception as exc:
            offered.append({"name": node.name, "reachable": False,
                            "resources": [], "capabilities": [], "error": str(exc)})
    return jsonify(resources=_resource_view(project), nodes=offered)


def _reread_on_node(project):
    """Re-read a node-backed image under the choice just recorded.

    Quiet about a node it cannot reach. The choice is saved either way, and
    `attach_image` applies it whenever the image is next attached -- so the
    worst case is the rebuild happening later rather than the answer being
    lost, and refusing the whole edit because a laptop went to sleep would be
    the wrong trade for a control that has already done the durable half of its
    job.
    """
    from plexora import nodes as node_api

    binding = project.resource("image")
    if binding is None or not binding.is_node:
        return
    try:
        node_api.attach_image(project.name, node=binding.node,
                              resource_id=binding.resource_id)
    except Exception:
        app.logger.warning(
            "could not re-read %r on node %r under its new image type",
            project.name, binding.node, exc_info=True)


@app.route('/project/<string:name>/resources/<string:kind>', methods=['POST'])
def project_attach_resource(name, kind):
    """Point one resource at a node, or bring it back to this machine.

    `node` absent means detach, and then `path` says where the file is on THIS
    machine -- required, because a resource that was on a node has no local
    copy by construction. Detaching leaves every answer the project has
    recorded about the resource -- roles, marker split, coordinate source --
    exactly as they were, because a table that comes home is not a table that
    has to be re-imported.
    """
    from plexora import nodes as node_api

    payload = request.get_json(silent=True) or {}
    node = (payload.get("node") or "").strip()
    resource_id = (payload.get("resource_id") or "").strip()

    if Project.find(name) is None:
        return jsonify(error="Unknown project"), 404
    try:
        if not node:
            node_api.detach(name, kind, path=payload.get("path"))
        elif kind == "table":
            node_api.attach_table(name, node=node, resource_id=resource_id)
        elif kind == "image":
            node_api.attach_image(name, node=node, resource_id=resource_id)
        elif kind == "segmentation":
            node_api.attach_segmentation(name, node=node, resource_id=resource_id)
        else:
            return jsonify(error=f"Unknown resource kind: {kind}"), 400
    except KeyError as exc:
        return jsonify(error=str(exc).strip("'\"")), 400
    except ValueError as exc:
        return jsonify(error=str(exc)), 400
    except Exception as exc:
        return jsonify(error=str(exc)), 502

    return jsonify(ok=True, resources=_resource_view(Project.load(name)))


def _editable_roles(project):
    """Which roles this project's user may reassign.

    All of them, for every format. `cell_id`, `x` and `y` used to be withheld
    from AnnData and SpatialData projects because the adapter synthesizes those
    columns, so repointing the role named a column the loaded table did not
    have. They are answerable now because the answer goes into the read spec
    instead -- which is the only way to say "the mask's label values are in this
    obs column", and without it a segmentation overlay could never line up.
    """
    return list(ROLE_NAMES) if project.has_table else []


def _needs_for_tool(project, tool_name):
    """The requirements a named tool is still missing, so the edit page can
    highlight exactly those fields. This is the no-JavaScript twin of the
    requirements modal -- same question, same answer, different surface."""
    if not tool_name:
        return None
    plugin = plugin_registry.find(app, tool_name)
    if plugin is None or not plugin.requires.applies_to(project):
        return None
    return {
        "tool": plugin.name,
        "label": plugin.label,
        "missing": [r.describe() for r in plugin.requires.missing_from(project)],
        "confirm": [r.describe() for r in plugin.requires.unconfirmed_from(project)],
        "optional": [r.describe() for r in plugin.requires.optional_missing_from(project)],
    }


@app.route('/project/<string:name>', methods=['POST'])
def save_project(name):
    """Apply an edit. Everything except the image can change.

    Merge semantics throughout: a key the request does not mention is carried
    across untouched. The expensive work -- re-reading a new data file,
    converting a new mask -- runs only when that input actually changed, which
    is what makes saving an unchanged form free.
    """
    payload = request.get_json(silent=True) or {}
    project = Project.find(name)
    if project is None:
        return jsonify(success=False, error="Unknown project"), 404

    try:
        changed = _apply_edit(project, payload)
    except ValueError as exc:
        # A bad path or an unreadable file is the user's to fix, and they need
        # to be told which. The old handler returned success=False with HTTP
        # 200 and no message, and the client navigated away regardless.
        return jsonify(success=False, error=str(exc)), 400

    if changed:
        # An answer is only accepted once the file can be read with it, so a
        # role that rewrites the read spec into something the adapter refuses
        # is put back rather than left stored -- see tool_routes.
        error = tool_routes._reload_or_restore(name, project)
        if error:
            return jsonify(success=False, error=error), 400

    project = Project.find(name)
    return jsonify(success=True, reloaded=changed,
                   segmentation_pending=project.segmentation.pending)


def _apply_edit(project, payload):
    """Returns whether anything changed that needs a datasource reload."""
    from plexora.server.providers.base import is_node_locator
    from plexora.server.routes import import_routes

    changed = False

    if "segmentation" in payload:
        wanted = (payload.get("segmentation") or "").strip() or None
        # What the field was showing -- the node address when the mask is on
        # one, because that is what `_describe` put in it. Comparing against a
        # local source path instead would read every save of an unrelated
        # setting as "the user cleared the mask".
        current = _segmentation_field(project)
        if (wanted or None) != (current or None):
            if (wanted and not is_node_locator(wanted)
                    and not Path(wanted).expanduser().exists()):
                raise ValueError(f"No such segmentation mask: {wanted}")
            # Local path, node address or empty -- attach_segmentation is the
            # one place that tells them apart, for all three surfaces.
            import_routes.attach_segmentation(project.name, wanted)
            changed = True

    swapped = False
    if "data" in payload:
        wanted = (payload.get("data") or "").strip() or None
        current = project.dataset.src if project.dataset else None
        # A different path is the obvious case. The other one is a source whose
        # PATH is unchanged and whose table has just been chosen -- which is
        # the whole shape of an unresolved project, and the only edit that
        # makes it readable. Comparing paths alone dropped that answer
        # silently: the user picked a table, pressed Save, and the project went
        # on being unreadable with nothing said.
        spec = project.dataset
        narrowed = wanted and spec is not None and (
            (payload.get("table") or None) != (spec.table or None)
            or ((payload.get("subset_column") or None)
                != ((spec.subset or {}).get("column") or None)))
        if (wanted or None) != (current or None) or narrowed:
            import_routes.replace_project_data(project.name, wanted, payload)
            changed = True
            swapped = True

    # Presence, not truth, for the same reason cellLayer is read that way below:
    # "" means Automatic, which is a change worth applying.
    if "imageType" in payload:
        wanted = (payload.get("imageType") or "").strip() or None
        if wanted != project.image.image_type_choice:
            updated = Project.mutate(project.name,
                                     lambda current: current.with_image_type(wanted))
            # Re-read only when the choice actually landed. `with_image_type`
            # ignores a value it does not recognise, and re-registering on that
            # would rebuild the project to say exactly what it already said.
            if updated and updated.image.image_type_choice == wanted:
                if project.image.src:
                    reregister_image(project.name)
                    changed = True
                else:
                    # An image on a data node has no local file to re-read, but
                    # it still has to be re-READ: the two modes disagree about
                    # the layer list -- one `rgb` layer or three channels --
                    # and recording the choice without rebuilding it left the
                    # control looking like it had done nothing.
                    #
                    # `attach_image` picks the stored choice up itself, so this
                    # is the same call the Attach control makes rather than a
                    # second way of applying an override. A project whose image
                    # is neither local nor on a node has nothing to rebuild;
                    # the choice stands for the next time it acquires one.
                    _reread_on_node(updated)
                    changed = True

    # Only when the file itself did not change: replace_project_data already
    # reads `features_layer` out of this same payload, and applying it twice
    # would validate the new choice against the old file's layer list.
    if not swapped:
        changed = apply_feature_choice(project, payload) or changed

    roles = payload.get("roles")
    columns = payload.get("columns")
    coordinates = payload.get("coordinates")
    single_image = payload.get("single_image")
    row_number_ids = payload.get("row_number_ids")
    # Presence, not truth: "" is the client saying "no override, draw whatever
    # this project resolves to", which is a change worth applying and would be
    # dropped by a plain truthiness test.
    chose_layer = "cellLayer" in payload
    cell_layer = payload.get("cellLayer")
    confirm = payload.get("confirm")
    if (roles or columns or coordinates or single_image or row_number_ids
            or chose_layer or confirm):
        def _apply(current):
            if columns:
                current = current.with_columns(columns.get("markers") or [],
                                               columns.get("metadata") or [])
            # The same helper the requirements modal applies its answers with,
            # so the two surfaces cannot disagree about what a payload means.
            current = tool_routes.apply_column_answers(current, payload)
            if chose_layer:
                current = current.with_cell_layer(cell_layer)
            # Saving this page is the user looking at these values and
            # accepting them, which is exactly what the requirements modal asks
            # for -- so a tool opened afterwards must not ask again.
            return current.with_confirmed(confirm or ())

        Project.mutate(project.name, _apply)
        # A cell-layer choice on its own changes nothing the datasource holds;
        # it is read from the config by the viewer. Reloading for it would
        # re-open the image to record a preference.
        changed = changed or bool(roles or columns or coordinates
                                  or row_number_ids)

    return changed


def apply_feature_choice(project, payload):
    """Point the reader at a matrix and/or switch the log1p transform.

    Shared with the requirements modal (tool_routes), because both surfaces ask
    the same question and getting the answer to stick means the same two writes.
    Returns whether anything changed -- both halves change what every number in
    the app is, so either one needs the datasource re-read.
    """
    layer = payload.get("features_layer")
    has_log = "features_log" in payload
    log = bool(payload.get("features_log"))
    wants_layer = bool(layer) and layer != project.feature_source
    wants_log = has_log and log != project.log_transformed
    if not wants_layer and not wants_log:
        return False

    # Read outside the write lock: the layer list may come off disk, and holding
    # config.json's lock across a file read serializes every other writer behind
    # it for no reason.
    layers = source_layers(project.dataset) if wants_layer else None

    def _change(current):
        # The available list goes in first, so a project imported before it was
        # recorded validates the choice against the file rather than against an
        # empty tuple that would reject every layer.
        if wants_layer:
            current = current.with_layers(layers).with_feature_source(layer)
        if wants_log:
            current = current.with_log_transform(log)
        return current

    Project.mutate(project.name, _change)
    return True


@app.route('/project/<string:name>/delete', methods=['POST'])
def delete_project(name):
    """Remove a project and everything derived for it.

    POST, not GET: this is an irreversible rmtree, and it used to sit behind a
    link that any crawler, prefetcher or stale bookmark could follow.
    """
    project = Project.find(name)
    if project is None:
        return jsonify(success=False, error="Unknown project"), 404
    if project.is_shared:
        # A shared project belongs to whoever provisioned the root it sits on.
        # Refused here rather than allowed to fail against a read-only
        # filesystem, so the answer is a sentence rather than a traceback --
        # and so a WRITABLE shared root cannot let one user delete a project
        # every other user on the machine is working from.
        return jsonify(
            success=False,
            error="This project is on a shared data directory and cannot be "
                  "deleted from Plexora.",
        ), 403

    project.delete()
    # The grouping goes with it. Here rather than inside `Project.delete()`:
    # that primitive is also how a half-finished registration is rolled back,
    # and a rollback must not reach into a file the failed import never
    # touched.
    datasets.forget_project(name)
    # Only this user's own copy of the project directory -- which is everything
    # Plexora put under its own root, and deliberately not the label pyramid it
    # derived beside the user's mask. That file is named after the mask rather
    # than after any project, other projects and data nodes may be serving it,
    # and it sits in a directory Plexora was invited into rather than one it
    # owns. Deleting a project is not permission to delete from there.
    directory = paths.project_state_dir(name)
    if directory.is_dir():
        shutil.rmtree(directory, ignore_errors=True)
    return jsonify(success=True)
