# Open Project page -- lists prior projects with search/sort/grid-list view,
# replacing the old inline project list in the File dropdown (base.html).
from plexora import app, get_config, data_path
from plexora.server.models import data_model
from plexora.server.routes.page_routes import template_data

from flask import render_template, jsonify, send_file, abort
from pathlib import Path
import datetime
import io

_THUMBNAIL_CACHE_NAME = '.thumbnail.webp'


@app.route('/open_project')
def open_project_page():
    return render_template('open_project.html', data=template_data())


def _fallback_timestamp(name):
    """Best-effort date for projects saved before createdAt/lastOpenedAt
    existed: macOS reports true creation time via st_birthtime, everything
    else falls back to st_ctime (metadata-change time, the closest
    approximation available)."""
    try:
        stat = (data_path / name).stat()
    except OSError:
        return None
    seconds = getattr(stat, 'st_birthtime', stat.st_ctime)
    return datetime.datetime.fromtimestamp(seconds).isoformat()


@app.route('/projects')
def list_projects():
    config = get_config()
    projects = []
    for name, entry in config.items():
        entry = entry or {}
        created_at = entry.get('createdAt') or _fallback_timestamp(name)
        last_opened_at = entry.get('lastOpenedAt') or created_at
        projects.append({
            'name': name,
            'createdAt': created_at,
            'lastOpenedAt': last_opened_at,
            'thumbnailUrl': f'/project_thumbnail/{name}',
        })
    return jsonify(projects)


@app.route('/project_thumbnail/<string:name>')
def project_thumbnail(name):
    config = get_config()
    if name not in config:
        abort(404)

    cache_path = data_path / name / _THUMBNAIL_CACHE_NAME
    if cache_path.exists():
        return send_file(cache_path, mimetype='image/webp')

    result = data_model.generate_thumbnail(name)
    if result is None:
        abort(404)
    encoded, mimetype = result
    try:
        cache_path.write_bytes(encoded)
    except OSError:
        pass  # Cache is best-effort -- still serve the freshly generated bytes.
    return send_file(io.BytesIO(encoded), mimetype=mimetype)
